openapi: 3.0.0
servers:
  - url: 'http://petstore.swagger.io/v2'
info:
  description: >-
    This APIs for iwf SDKs to operate workflows
  version: 1.0.0
  title: Workflow APIs
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  # workflow APIs are hosted by iWF server for iWF SDKs to call
  /api/v1/workflow/start:
    post:
      summary: "start a workflow"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowStartRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStartResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/workflow/signal:
    post:
      summary: "signal a workflow"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowSignalRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowSignalResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/workflow/query:
    post:
      summary: "query a workflow"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowQueryRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowQueryResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/workflow/get:
    post:
      summary: "get a workflow's status and results(if completed & requested)"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowGetRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowGetResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/workflow/getWithLongWait: ## this will wait for workflow to close if still running
    post:
      summary: "get a workflow's status and results(if completed & requested), wait if the workflow is still running"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowGetRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowGetResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/workflow/search:
    post:
      summary: "search for workflows by a search attribute query"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowSearchRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowSearchResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  # workflowState APIs are hosted by iWF SDK for iWF server to call
  /api/v1/workflowState/start:
    post:
      summary: "for invoking WorkflowState.start API"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowStateStartRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStateStartResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/workflowState/decide:
    post:
      summary: "for invoking WorkflowState.decide API"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowStateDecideRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStateDecideResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'                
components:
  schemas:
    KeyValue:
      type: object
      properties:
        key:
          type: string
        value:
          $ref: '#/components/schemas/EncodedObject'
    EncodedObject:
      type: object
      properties:
        encoding:
          type: string
          enum:
            - JSON
        data:
          type: string
    SearchAttribute:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
        valueType:
          type: string
          enum:
            - KEYWORD
            - INT
    WorkflowStateOptions:
      type: object
      properties:
        searchAttributesLoadingPolicy:
          $ref: '#/components/schemas/AttributesLoadingPolicy'
        queryAttributesLoadingPolicy:
          $ref: '#/components/schemas/AttributesLoadingPolicy'
        commandCarryOverPolicy:
          $ref: '#/components/schemas/CommandCarryOverPolicy'
    AttributesLoadingPolicy:
      type: object
      properties:
        attributeLoadingType:
          type: string
          enum:
            - LOAD_ALL_WITHOUT_LOCKING
            - LOAD_ALL_WITH_EXCLUSIVE_LOCK
            - LOAD_PARTIAL_WITHOUT_LOCKING
            - LOAD_PARTIAL_WITH_EXCLUSIVE_LOCK
        attributeKeys:
          type: array
          items:
            type: string
    CommandCarryOverPolicy:
      type: object
      properties:
        commandCarryOverType:
          type: string
          enum:
            - NONE
            - ALL_UNFINISHED
    ErrorResponse:
      type: object
      properties:
        detail: 
          type: string
        subStatus: 
          type: string  
    WorkflowStartRequest:
      type: object
      required:
        - workflowId
        - iwfWorkerUrl
        - iwfWorkflowType
        - startStateId
        - workflowTimeoutSeconds
      properties:
        workflowId:
          type: string
        iwfWorkflowType:
          type: string
        workflowTimeoutSeconds:
          type: integer
        iwfWorkerUrl:
          type: string
        startStateId:
          type: string
        stateInput:
          $ref: '#/components/schemas/EncodedObject'
        stateOptions:
          $ref: '#/components/schemas/WorkflowStateOptions'
    WorkflowStartResponse:
      type: object
      properties:
        workflowRunId:
          type: string
    WorkflowSignalRequest:
      type: object
      required:
        - workflowId
        - signalName
      properties:
        workflowId:
          type: string
        workflowRunId:
          type: string
        signalName:
          type: string
        signalValue:
          $ref: '#/components/schemas/EncodedObject'
    WorkflowSignalResponse:
      type: object
      properties: {}
    WorkflowQueryRequest:
      type: object
      required:
        - workflowId
      properties:
        workflowId:
          type: string
        workflowRunId:
          type: string
        attributeKeys: # return all attributes if this is empty
          type: array
          items:
            type: string
    WorkflowQueryResponse:
      type: object
      properties:
        queryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
    WorkflowGetRequest:
      type: object
      required:
        - workflowId
      properties:
        workflowId:
          type: string
        workflowRunId:
          type: string
        needsResults: # result will be return if this is true, and workflow is completed
          type: boolean
    WorkflowGetResponse:
      type: object
      required:
        - workflowRunId
        - workflowStatus
      properties:
        workflowRunId:
          type: string
        workflowStatus:
          type: string
          enum:
            - RUNNING
            - COMPLETED
            - FAILED
            - TIMEOUT
            - TERMINATED
            - CANCELED
            - CONTINUED_AS_NEW
        results: # result will be return if needsResults is true in request, and workflow is completed
          type: array
          items:
            $ref: '#/components/schemas/StateCompletionOutput'
    StateCompletionOutput:
      type: object
      required:
        - completedStateExecutionId
        - completedStateId
      properties:
        completedStateId:
          type: string
        completedStateExecutionId:
          type: string
        completedStateOutput:
          $ref: '#/components/schemas/EncodedObject'
    WorkflowSearchRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
        pageSize:
          type: integer
          format: int32
    WorkflowSearchResponse:
      type: object
      properties:
        workflowExecutions:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowSearchResponseEntry'
    WorkflowSearchResponseEntry:
      type: object
      properties:
        workflowId:
          type: string
        workflowRunId:
          type: string
    WorkflowStateStartRequest:
      type: object
      required:
        - context
        - workflowStateId
        - workflowType
      properties:
        context:
          $ref: '#/components/schemas/Context'
        workflowType:
          type: string
        workflowStateId:
          type: string
        stateInput:
          $ref: '#/components/schemas/EncodedObject'
        searchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/SearchAttribute'
        queryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
    WorkflowStateStartResponse:
      type: object
      properties:
        upsertSearchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/SearchAttribute'
        upsertQueryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        commandRequest:
          $ref: '#/components/schemas/CommandRequest'
        upsertStateLocalAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
    WorkflowStateDecideRequest:
      type: object
      required:
        - context
        - workflowType
        - workflowStateId
      properties:
        context:
          $ref: '#/components/schemas/Context'
        workflowType:
          type: string
        workflowStateId:
          type: string
        stateInput:
          $ref: '#/components/schemas/EncodedObject'
        searchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/SearchAttribute'
        queryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        stateLocalAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        commandResults:
          $ref: '#/components/schemas/CommandResults'
    WorkflowStateDecideResponse:
      type: object
      properties:
        stateDecision:
          $ref: '#/components/schemas/StateDecision'
    StateDecision:
      type: object
      properties:
        waitForMoreCommandResults:
          type: boolean
        nextStates:
          type: array
          items:
            $ref: '#/components/schemas/StateMovement'
        upsertSearchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/SearchAttribute'
        upsertQueryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
    StateMovement:
      type: object
      required:
        - stateId
      properties:
        stateId:
          type: string
        nextStateInput:
          $ref: '#/components/schemas/EncodedObject'
        nextStateOptions:
          $ref: '#/components/schemas/WorkflowStateOptions'
    CommandRequest:
      type: object
      required:
        - deciderTriggerType
      properties:
        deciderTriggerType:
          type: string
          enum:
            - ALL_COMMAND_COMPLETED
            - ANY_COMMAND_COMPLETED
            - ANY_COMMAND_CLOSED
        activityCommands:
          type: array
          items:
            $ref: '#/components/schemas/ActivityCommand'
        timerCommands:
          type: array
          items:
            $ref: '#/components/schemas/TimerCommand'
        signalCommands:
          type: array
          items:
            $ref: '#/components/schemas/SignalCommand'
    CommandResults:
      type: object
      properties:
        activityResults:
          type: array
          items:
            $ref: '#/components/schemas/ActivityResult'
        signalResults:
          type: array
          items:
            $ref: '#/components/schemas/SignalResult'
        timerResults:
          type: array
          items:
            $ref: '#/components/schemas/TimerResult'
    ActivityCommand:
      required:
        - commandId
        - activityType
      type: object
      properties:
        commandId:
          type: string
        activityType:
          type: string
        input:
          $ref: '#/components/schemas/EncodedObject'
        activityOptions:
          $ref: '#/components/schemas/ActivityOptions'
    TimerCommand:
      type: object
      required:
        - commandId
        - firingUnixTimestampSeconds
      properties:
        commandId:
          type: string
        firingUnixTimestampSeconds:
          type: integer
          format: int64
    SignalCommand:
      type: object
      required:
        - commandId
        - signalName
      properties:
        commandId:
          type: string
        signalName:
          type: string
    ActivityOptions:
      type: object
      properties:
        startToCloseTimeoutSeconds:
          type: integer
    ActivityResult:
      type: object
      required:
        - commandId
        - activityType
        - activityStatus
      properties:
        commandId:
          type: string
        activityType:
          type: string
        output:
          $ref: '#/components/schemas/EncodedObject'
        activityStatus:
          type: string
          enum:
            - OPEN
            - COMPLETED
            - TIMEOUT
            - FAILED
        timeoutType:
          type: string
          enum:
            - SCHEDULED_TO_START
            - START_TO_CLOSE
            - SCHEDULE_TO_CLOSE
            - HEARTBEAT
    TimerResult:
      type: object
      required:
        - commandId
        - timerStatus
      properties:
        commandId:
          type: string
        timerStatus:
          type: string
          enum:
            - SCHEDULED
            - FIRED
    SignalResult:
      type: object
      required:
        - commandId
        - signalName
        - signalStatus
      properties:
        commandId:
          type: string
        signalStatus:
          type: string
          enum:
            - WAITING
            - RECEIVED
        signalName:
          type: string
        signalValue:
          $ref: '#/components/schemas/EncodedObject'
    Context:
      type: object
      required:
        - commandId
        - workflowId
        - workflowRunId
        - workflowStartedTimestamp
        - stateExecutionId
      properties:
        workflowId:
          type: string
        workflowRunId:
          type: string
        workflowStartedTimestamp:
          type: integer
          format: int64
        stateExecutionId:
          type: string          
