openapi: 3.0.0
servers:
  - url: 'http://petstore.swagger.io/v2'
info:
  description: >-
    This APIs for iwf-server to invoke user workflow code defined in WorkflowState using any iwf SDKs
  version: 1.0.0
  title: WorkflowState APIs
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /api/v1/workflowState/start:
    post:
      summary: "for invoking WorkflowState.start API"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowStateStartRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStateStartResponse'
        '405':
          description: Invalid input
  /api/v1/workflowState/decide:
    post:
      summary: "for invoking WorkflowState.decide API"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowStateDecideRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStateDecideResponse'
        '405':
          description: Invalid input
components:
  schemas:
    WorkflowStateStartRequest:
      type: object
      properties:
        workflowType:
          type: string
        workflowStateId:
          type: string
        searchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        queryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
    WorkflowStateStartResponse:
      type: object
      properties:
        upsertSearchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        upsertQueryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        commandRequest:
          $ref: '#/components/schemas/CommandRequest'
    WorkflowStateDecideRequest:
      type: object
      properties:
        workflowType:
          type: string
        workflowStateId:
          type: string
        searchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        queryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        commandRequest:
          $ref: '#/components/schemas/CommandRequest'
    WorkflowStateDecideResponse:
      type: object
      properties:
        stateDecision:
          type: object
          items:
            $ref: '#/components/schemas/StateDecision'
    StateDecision:
      type: object
      properties:
        waitForMoreCommandResults:
          type: boolean
        nextStates:
          type: array
          items:
            $ref: '#/components/schemas/StateMovement'
        upsertSearchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        upsertQueryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
    StateMovement:
      type: object
      properties:
        stateId:
          type: string
        nextStateInput:
          type: string
    CommandRequest:
      type: object
      properties:
        deciderTriggerType:
          type: string
          enum:
            - ALL_COMMAND_COMPLETED
            - ANY_COMMAND_COMPLETED
            - ANY_COMMAND_CLOSED
        activityCommands:
          type: array
          items:
            $ref: '#/components/schemas/ActivityCommand'
    KeyValue:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ActivityCommand:
      type: object
      properties:
        commandId:
          type: string
        activityType:
          type: string
        input:
          type: string
        activityOptions:
          $ref: '#/components/schemas/ActivityOptions'
    ActivityOptions:
      type: object
      properties:
        startToCloseTimeoutSeconds:
          type: integer


