openapi: 3.0.0
servers:
  - url: 'http://petstore.swagger.io/v2'
info:
  description: >-
    This APIs for iwf-server to invoke user workflow code defined in WorkflowState using any iwf SDKs
  version: 1.0.0
  title: WorkflowState APIs
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /api/v1/workflowState/start:
    post:
      summary: "for invoking WorkflowState.start API"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowStateStartRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStateStartResponse'
        '405':
          description: Invalid input
  /api/v1/workflowState/decide:
    post:
      summary: "for invoking WorkflowState.decide API"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowStateDecideRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStateDecideResponse'
        '405':
          description: Invalid input
components:
  schemas:
    WorkflowStateStartRequest:
      type: object
      properties:
        context:
          $ref: '#/components/schemas/Context'
        workflowType:
          type: string
        workflowStateId:
          type: string
        stateInput:
          $ref: '#/components/schemas/EncodedObject'
        searchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        queryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
    WorkflowStateStartResponse:
      type: object
      properties:
        upsertSearchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        upsertQueryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        commandRequest:
          $ref: '#/components/schemas/CommandRequest'
        upsertStateLocalAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
    WorkflowStateDecideRequest:
      type: object
      properties:
        context:
          $ref: '#/components/schemas/Context'
        workflowType:
          type: string
        workflowStateId:
          type: string
        searchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        queryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        stateLocalAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        commandResults:
          $ref: '#/components/schemas/CommandResults'
    WorkflowStateDecideResponse:
      type: object
      properties:
        stateDecision:
          type: object
          items:
            $ref: '#/components/schemas/StateDecision'
    StateDecision:
      type: object
      properties:
        waitForMoreCommandResults:
          type: boolean
        nextStates:
          type: array
          items:
            $ref: '#/components/schemas/StateMovement'
        upsertSearchAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        upsertQueryAttributes:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
    StateMovement:
      type: object
      properties:
        stateId:
          type: string
        nextStateInput:
          $ref: '#/components/schemas/EncodedObject'
    CommandRequest:
      type: object
      properties:
        deciderTriggerType:
          type: string
          enum:
            - ALL_COMMAND_COMPLETED
            - ANY_COMMAND_COMPLETED
            - ANY_COMMAND_CLOSED
        activityCommands:
          type: array
          items:
            $ref: '#/components/schemas/ActivityCommand'
        timerCommands:
          type: array
          items:
            $ref: '#/components/schemas/TimerCommand'
        signalCommands:
          type: array
          items:
            $ref: '#/components/schemas/SignalCommand'
    CommandResults:
      type: object
      properties:
        activityResults:
          type: array
          items:
            $ref: '#/components/schemas/ActivityResult'
        signalResults:
          type: array
          items:
            $ref: '#/components/schemas/SignalResult'
        timerResults:
          type: array
          items:
            $ref: '#/components/schemas/TimerResult'
    KeyValue:
      type: object
      properties:
        key:
          type: string
        value:
          $ref: '#/components/schemas/EncodedObject'
    EncodedObject:
      type: object
      properties:
        encoding:
          type: string
          enum:
            - JSON
        data:
          type: string
    ActivityCommand:
      type: object
      properties:
        commandId:
          type: string
        activityType:
          type: string
        input:
          $ref: '#/components/schemas/EncodedObject'
        activityOptions:
          $ref: '#/components/schemas/ActivityOptions'
    TimerCommand:
      type: object
      properties:
        commandId:
          type: string
        firingUnixTimestampSeconds:
          type: integer
    SignalCommand:
      type: object
      properties:
        commandId:
          type: string
        signalName:
          type: string
    ActivityOptions:
      type: object
      properties:
        startToCloseTimeoutSeconds:
          type: integer
    ActivityResult:
      type: object
      properties:
        commandId:
          type: string
        activityType:
          type: string
        output:
          $ref: '#/components/schemas/EncodedObject'
        activityStatus:
          type: string
          enum:
            - OPEN
            - COMPLETED
            - TIMEOUT
            - FAILED
        timeoutType:
          type: string
          enum:
            - SCHEDULED_TO_START
            - START_TO_CLOSE
            - SCHEDULE_TO_CLOSE
            - HEARTBEAT
    TimerResult:
      type: object
      properties:
        commandId:
          type: string
        timerStatus:
          type: string
          enum:
            - SCHEDULED
            - FIRED
    SignalResult:
      type: object
      properties:
        commandId:
          type: string
        signalStatus:
          type: string
          enum:
            - WAITING
            - RECEIVED
        signalName:
          type: string
        signalValue:
          $ref: '#/components/schemas/EncodedObject'
    Context:
      type: object
      properties:
        workflowId:
          type: string
        workflowRunId:
          type: string
        workflowStartedTimestamp:
          type: integer
        stateExecutionId:
          type: string



